"""
Regression harness — seed corpus from actual games and standard positions.

Run: python3 -m pytest test_regression.py -v
"""

import unittest
import chess
from perception import cmd_validate


# ---------------------------------------------------------------------------
# Corpus: only positions from actual games or universally known openings.
# NO positions generated by the LLM.
# ---------------------------------------------------------------------------

CORPUS = [
    # --- Actual game: 1.d4 d5 2.Nc3 Nf6 3.Bf4 Nc6 4.Nb5 ---
    {
        "id": "game1_a6_fork",
        "fen": "r1bqkb1r/ppp1pppp/2n2n2/1N1p4/3P1B2/8/PPP1PPPP/R2QKBNR b KQkq - 5 4",
        "test_move": "a6",
        "expected_pass": False,
        "motif": "check-fork",
        "note": "a6 allows Nxc7+ forking king and rook — every evasion loses material",
    },
    {
        "id": "game1_Bd7_also_fails",
        "fen": "r1bqkb1r/ppp1pppp/2n2n2/1N1p4/3P1B2/8/PPP1PPPP/R2QKBNR b KQkq - 5 4",
        "test_move": "Bd7",
        "expected_pass": False,
        "motif": "check-fork",
        "note": "Bd7 does NOT block Nxc7+ — knight still forks king+rook",
    },
    # --- Actual game: 1.d4 Nf6 2.Nf3 e6 3.Bf4 c5 4.e3 d5 5.Nc3 Be7 6.Nb5 ---
    {
        "id": "game2_oo_rook_loss",
        "fen": "rnbqk2r/pp2bppp/4pn2/1NpP4/5B2/4P3/PPP2PPP/R2QKBNR b KQkq - 0 6",
        "test_move": "O-O",
        "expected_pass": False,
        "motif": "non-check-quiet-threat",
        "note": "O-O allows Nc7 creating a hanging rook on a8 (value 5). Now hard-fails.",
    },
    # --- Standard openings after 1.e4 ---
    {
        "id": "opening_1e4_d5",
        "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        "test_move": "d5",
        "expected_pass": True,
        "motif": "safe-opening",
        "note": "Scandinavian — Bb5+ is a harmless check",
    },
    {
        "id": "opening_1e4_e5",
        "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        "test_move": "e5",
        "expected_pass": True,
        "motif": "safe-opening",
        "note": "Classical — standard reply",
    },
    {
        "id": "opening_1e4_c5",
        "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        "test_move": "c5",
        "expected_pass": True,
        "motif": "safe-opening",
        "note": "Sicilian — standard reply",
    },
    {
        "id": "opening_1e4_c6",
        "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
        "test_move": "c6",
        "expected_pass": True,
        "motif": "safe-opening",
        "note": "Caro-Kann — our repertoire",
    },
    # --- Standard openings after 1.d4 ---
    {
        "id": "opening_1d4_d5",
        "fen": "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
        "test_move": "d5",
        "expected_pass": True,
        "motif": "safe-opening",
        "note": "QGD — our repertoire",
    },
    {
        "id": "opening_1d4_Nf6",
        "fen": "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
        "test_move": "Nf6",
        "expected_pass": True,
        "motif": "safe-opening",
        "note": "Indian — standard reply",
    },
    # --- Scholar's mate: 1.e4 e5 2.Bc4 Nc6 3.Qh5 ---
    {
        "id": "scholars_g6_defense",
        "fen": "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3",
        "test_move": "g6",
        "expected_pass": True,
        "motif": "safe-defense",
        "note": "g6 attacks the queen on h5, forcing it to move — blocks mate",
    },
    {
        "id": "scholars_Qe7_defense",
        "fen": "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3",
        "test_move": "Qe7",
        "expected_pass": True,
        "motif": "safe-defense",
        "note": "Qe7 blocks Qxf7# by defending f7",
    },
    {
        "id": "scholars_Nf6_fails",
        "fen": "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3",
        "test_move": "Nf6",
        "expected_pass": False,
        "motif": "immediate-mate",
        "note": "Nf6 attacks queen but does NOT block Qxf7# — queen bypasses f6",
    },
    # --- Alekhine: 1.e4 Nf6 2.e5 ---
    {
        "id": "alekhine_Nd5",
        "fen": "rnbqkb1r/pppppppp/5n2/4P3/8/8/PPPP1PPP/RNBQKBNR b KQkq - 0 2",
        "test_move": "Nd5",
        "expected_pass": True,
        "motif": "safe-retreat",
        "note": "Nd5 retreats knight to safe central square",
    },
]


class RegressionTests(unittest.TestCase):
    """Run each corpus position through cmd_validate and check pass/fail."""

    def _run_case(self, case):
        board = chess.Board(case["fen"])
        move = board.parse_san(case["test_move"])
        self.assertIn(move, board.legal_moves, f"{case['id']}: {case['test_move']} is not legal")

        result = cmd_validate(board, case["test_move"], as_json=True)
        return result

    def test_corpus_pass_fail(self):
        """All cases with expected_pass=True/False must match."""
        for case in CORPUS:
            if case["expected_pass"] is None:
                continue  # documented gap, skip
            with self.subTest(case=case["id"]):
                result = self._run_case(case)
                if case["expected_pass"]:
                    self.assertTrue(
                        result["passed"],
                        f"{case['id']}: expected PASS but got FAIL — {result['hard_failures']}"
                    )
                else:
                    self.assertFalse(
                        result["passed"],
                        f"{case['id']}: expected FAIL but got PASS — {result['explanation']}"
                    )

    def test_documented_gaps(self):
        """Cases with expected_pass=None are known gaps. Print status for visibility."""
        for case in CORPUS:
            if case["expected_pass"] is not None:
                continue
            result = self._run_case(case)
            status = "PASS" if result["passed"] else "FAIL"
            print(f"  GAP {case['id']}: validator says {status} — {case['note']}")


if __name__ == "__main__":
    unittest.main()
